version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    env_file:
      - ./docker-env/.env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
    links:
      - postgres
    ports:
      - 3000:3000

  postgres:
    container_name: database
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_EXTERNAL_PORT}:${DB_PORT}'
    volumes:
      - car_rent_api:/var/lib/postgresql/data

volumes:
  car_rent_api:
