version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    depends_on:
      - postgres
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000

  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_EXTERNAL_PORT}:${DB_EXTERNAL_PORT}'
    volumes:
      - car_rent_api:/var/lib/postgresql/data

volumes:
  car_rent_api:
